server {
    listen 80;
    server_name docker-nybest.appworkdemo.com;

    root /var/www/html/public;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    client_max_body_size 256M;

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    

        # Serve static files directly
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|webp|mp4|mp3|avi|mov)$ {
        expires max;
        log_not_found off;
        access_log off;
    }

    location ~ /\.(ht|env) {
        deny all;
    }

    location ~ /(config|database|resources|tests)/ {
        deny all;
    }

    location /vendor {
        deny all;
        return 403;
    }

    error_log  /var/log/nginx/laravel_error.log;
    access_log /var/log/nginx/laravel_access.log;
}
